### ISSUE TITLE
how to login?

### ISSUE THREAD

**Issue by boyfromhell** [ebussola/octobercms-user-facebook#1]
hey
very nice but as you can login
register?

**Comment by shina** [comment]
Hello, the plugin is beta yet. 
However you can try to use it by overriding the config file to your needs. (explained here: https://octobercms.com/docs/plugin/settings#file-configuration)

And use the FacebookSession component together with the Session component provided by RainLab.User

Then, configure the login button widget (https://developers.facebook.com/docs/facebook-login/login-flow-for-web/v2.2?locale=en_GB) to call `userFacebook.onLoginWithFacebook()` on "onlogin" event.

I hope it helps.
